import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/navbar";
import { Toaster } from "react-hot-toast";
import { Providers } from "./redux/provider/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={` antialiased bg-[linear-gradient(to_bottom,var(--primary),var(--secondary))] min-h-screen`}
      ><Toaster>
        </Toaster>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
